### ISSUE TITLE
http-password not showing on badsite.io index?

### ISSUE THREAD

**Issue by mozfreddyb** [april/badsite.io#1]
I was trying to find a test case for an http passowrd input field, but had to dig through the source code to find http://http-password.badsite.io/ - how come it is not linked from your index page?

**Comment by april** [comment]
Ahh, because I don't link in things that are mirrors of stuff that is on BadSSL:

http://http-password.badssl.com/

This is something that should probably just live on badsite.io, but I moving it involves work and redirects and etc. etc.
