### ISSUE TITLE
SSL/TLS cert expired May 2, 2019

### ISSUE THREAD

**Issue by nitrohorse** [april/badsite.io#2]
Hey, just an FYI, looks like badsite.io's SSL/TLS cert expired May 2, 2019.

![badsite-cert](https://user-images.githubusercontent.com/1514352/57988411-6a093600-7a7d-11e9-9d17-f382a4f13f6a.png)

**Comment by mozfreddyb** [comment]
works again. thanks @april

**Comment by april** [comment]
Sorry, I'm lazy.  😰

**Comment by nitrohorse** [comment]
Thank you!
